# Basic Level Scikit-learn Exercises (5 Exercises + Full Solutions)

These exercises are designed to build your strong foundation in:

- dataset handling
- train-test split
- model training
- prediction
- evaluation
- preprocessing
- classification
- regression

# Exercise 1 — Load Dataset and Explore It
**Objective**

Learn:

- how to load datasets
- understand features and target
- dataset structure  

**Problem**

Using the Iris dataset:

- Load the dataset
- Print feature names
- Print target names
- Print shape of dataset
- Print first 5 rows

In [2]:
from sklearn.datasets import load_iris
import pandas as pd

# Load dataset
iris = load_iris()

# Features and target
X = iris.data
y = iris.target

# Convert to DataFrame
df = pd.DataFrame(X, columns=iris.feature_names)

# Print feature names
print("Feature Names:")
print(iris.feature_names)

# Print target names
print("\nTarget Names:")
print(iris.target_names)

# Print shape
print("\nDataset Shape:")
print(df.shape)

# Print first 5 rows
print("\nFirst 5 Rows:")
print(df.head())

Feature Names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Names:
['setosa' 'versicolor' 'virginica']

Dataset Shape:
(150, 4)

First 5 Rows:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


# Exercise 2 — Train/Test Split
**Objective**

Learn:

- how to divide data
- training vs testing  

**Problem**

Using Iris dataset:

- Split dataset into training and testing
- Use 80% training and 20% testing
- Print shapes of train/test data

In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load dataset
iris = load_iris()

X = iris.data
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Print shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (120, 4)
X_test shape: (30, 4)
y_train shape: (120,)
y_test shape: (30,)


# Exercise 3 — First Classification Model
**Objective**

Learn:

- model creation
- training
- prediction
- accuracy calculation  

**Problem**

Using Iris dataset:

- Train a Decision Tree model
- Predict test data
- Calculate accuracy

In [8]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load dataset
iris = load_iris()

X = iris.data
y = iris.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Create model
model = DecisionTreeClassifier()

# Train model
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Predictions:")
print(y_pred)

print(f"Accuracy: {accuracy * 100:.2f} %")

Predictions:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Accuracy: 100.00 %


# Exercise 4 — Feature Scaling
**Objective**

Learn:
- preprocessing
- normalization/scaling  

**Problem**

Using a small dataset:
- Scale features using StandardScaler
- Print original and scaled data

In [9]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Sample data
data = np.array([
    [1000, 20],
    [1500, 25],
    [2000, 30],
    [2500, 35]
])

print("Original Data:")
print(data)

# Create scaler
scaler = StandardScaler()

# Scale data
scaled_data = scaler.fit_transform(data)

print("\nScaled Data:")
print(scaled_data)

Original Data:
[[1000   20]
 [1500   25]
 [2000   30]
 [2500   35]]

Scaled Data:
[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]


# Exercise 5 — Simple Linear Regression
Objective

Learn:

- regression
- prediction of continuous values  

Problem

Predict student marks from study hours.  
Tasks:

- Train Linear Regression model
- Predict marks for 6 hours

In [16]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Input data
X = np.array([[1], [2], [3], [4], [5]])

# Output data
y = np.array([20, 40, 50, 60, 80])

# Create model
model = LinearRegression()

# Train model
model.fit(X, y)

# Predict
prediction = model.predict([[6]])

print(f"\nPredicted Marks for 6 Hours:\n{prediction[0]:.2f}")


Predicted Marks for 6 Hours:
92.00


# Important Beginner Concepts You Just Practiced
Data Handling  
- loading datasets
- features
- labels
Preprocessing  
- scaling
Model Training  
- fit()
Prediction  
- predict()
Evaluation  
- accuracy
Supervised Learning  
- classification
- regression