# Intermediate Level Scikit-learn Exercises (5 Exercises + Full Solutions)

Now we move into the REAL practical foundation of Scikit-learn.

**At this stage, you will learn:**

- confusion matrix
- preprocessing
- pipelines
- missing value handling
- model comparison
- cross validation
- clustering
- PCA
- hyperparameter tuning

**These concepts are heavily used in:**

- real-world ML projects
- internships
- AI research
- Kaggle competitions
- smart traffic systems
- industry ML pipelines

# Exercise 1 — Confusion Matrix + Classification Report
Objective

Learn:

- evaluation metrics
- confusion matrix
- precision
- recall
- F1-score
- Problem

Using Iris dataset:

1. Train Logistic Regression model
2. Predict test data  
3. Print:
    - confusion matrix
    - classification report
    - accuracy

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score
)

# Load dataset
iris = load_iris()

X = iris.data
y = iris.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Create model
model = LogisticRegression(max_iter=200)

# Train model
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

# Classification Report
report = classification_report(y_test, y_pred)

print("Accuracy:")
print(accuracy)

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(report)

Accuracy:
1.0

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# **Exercise 2 — Handling Missing Values + Scaling**
**Objective**

Learn:

- missing value handling
- preprocessing
- scaling  

**Problem**
- Create dataset with missing values
- Fill missing values using mean
- Scale data using StandardScaler

In [13]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# Dataset with missing values
data = np.array([
    [1, 2000],
    [2, 3000],
    [np.nan, 4000],
    [4, np.nan],
    [5, 6000]
])

print("Original Data:")
print(data)

# Handle missing values
imputer = SimpleImputer(strategy='mean')

filled_data = imputer.fit_transform(data)

print("\nAfter Handling Missing Values:")
print(filled_data)

# Scaling
scaler = StandardScaler()

scaled_data = scaler.fit_transform(filled_data)

print("\nScaled Data:")
print(scaled_data)

Original Data:
[[1.e+00 2.e+03]
 [2.e+00 3.e+03]
 [   nan 4.e+03]
 [4.e+00    nan]
 [5.e+00 6.e+03]]

After Handling Missing Values:
[[1.00e+00 2.00e+03]
 [2.00e+00 3.00e+03]
 [3.00e+00 4.00e+03]
 [4.00e+00 3.75e+03]
 [5.00e+00 6.00e+03]]

Scaled Data:
[[-1.41421356 -1.32287566]
 [-0.70710678 -0.56694671]
 [ 0.          0.18898224]
 [ 0.70710678  0.        ]
 [ 1.41421356  1.70084013]]


# **Exercise 3 — Pipeline Creation**
Objective

Learn:

- ML workflow automation
- preprocessing + model together
- Problem

Using Iris dataset:

- Create pipeline
- Scale features
- Train SVM model
- Predict accuracy

In [14]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load dataset
iris = load_iris()

X = iris.data
y = iris.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Create pipeline
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SVC())
])

# Train
pipe.fit(X_train, y_train)

# Predict
y_pred = pipe.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:")
print(f"{accuracy * 100:.2f} %")

Accuracy:
100.00 %


# Exercise 4 — Cross Validation + Model Comparison
Objective

Learn:

- better evaluation
- comparing algorithms  

Problem

Using Iris dataset:

1. Compare:
    - Logistic Regression
    - Decision Tree
    - KNN
2. Use cross validation
3. Print average accuracy

In [17]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

# Load dataset
iris = load_iris()

X = iris.data
y = iris.target

# Models
models = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "Decision Tree": DecisionTreeClassifier(),
    "KNN": KNeighborsClassifier()
}

# Compare models
for name, model in models.items():

    scores = cross_val_score(
        model,
        X,
        y,
        cv=5
    )

    print(f"\n{name}")

    print("Scores:", scores)

    print("Average Accuracy:", f"{scores.mean() * 100:.2f} %")


Logistic Regression
Scores: [0.96666667 1.         0.93333333 0.96666667 1.        ]
Average Accuracy: 97.33 %

Decision Tree
Scores: [0.96666667 0.96666667 0.9        1.         1.        ]
Average Accuracy: 96.67 %

KNN
Scores: [0.96666667 1.         0.93333333 0.96666667 1.        ]
Average Accuracy: 97.33 %


# Exercise 5 — K-Means Clustering + PCA
Objective

Learn:

- unsupervised learning
- clustering
- dimensionality reduction  

Problem

Using Iris dataset:

- Apply KMeans clustering
- Reduce dimensions using PCA
- Print transformed data

In [18]:
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Load dataset
iris = load_iris()

X = iris.data

# KMeans clustering
kmeans = KMeans(
    n_clusters=3,
    random_state=42
)

clusters = kmeans.fit_predict(X)

print("Cluster Labels:")
print(clusters)

# PCA
pca = PCA(n_components=2)

X_pca = pca.fit_transform(X)

print("\nPCA Reduced Data:")
print(X_pca[:5])

Cluster Labels:
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 2 2 0 0 0 0 2 0 2 0 2 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 2 0 0 0 2 0
 0 2]

PCA Reduced Data:
[[-2.68412563  0.31939725]
 [-2.71414169 -0.17700123]
 [-2.88899057 -0.14494943]
 [-2.74534286 -0.31829898]
 [-2.72871654  0.32675451]]
